### ISSUE TITLE
Any way to use Audiomer in streaming mode?

### ISSUE THREAD

**Issue by wesbz** [The-Learning-Machines/Audiomer-PyTorch#2]
Hi
Cool work done here with Audiomer!
I was curious to know if it could be modified to work in streaming mode? Keyword spotting mostly makes sense as such.
Thanks in advance :)

**Comment by ojus1** [comment]
Hi!
Thanks for your interest in our work.

This particular implementation doesn't support streaming mode, since it is an encoder-only model, however a recent paper, https://arxiv.org/abs/2002.02562 shows a way to make transformer models support streaming mode using masking. I don't see any reason the techniques from this paper can't be applied to make our model to support streaming mode. 

Hope that answers your question.
Thanks.
